name: Build and deploy to cloudflare
on:
  push:
    branches:
      - "**"
      - "!master"
      - "!development"
      - "!cms/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1

      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}

      - name: Install Project Dependencies
        run: yarn install

      - name: Build Project
        run: npx gatsby build --prefix-paths

      - name: List output files
        run: ls -laFG

      - name: Install wrangler
        run: npm install -g wrangler@3.80

      - name: Publish to Cloudflare Pages
        id: cloudflare_pages_deploy
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy ./public --project-name=nuocw-release --commit-dirty=true

      - name: create job summary
        run: |
          echo "## Cloudflare Pages Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "| Name | Result |" >> $GITHUB_STEP_SUMMARY
          echo "| :-- | :-- |" >> $GITHUB_STEP_SUMMARY
          echo "| **Last commit:** | [${{ github.sha }}](https://github.com/NUOCW-Project/nuocw-release/commit/${{ github.sha }}) |" >> $GITHUB_STEP_SUMMARY
          echo "| **Preview URL**: | ${{ steps.cloudflare_pages_deploy.outputs.deployment-url }} |" >> $GITHUB_STEP_SUMMARY
          echo "| **Branch Preview URL**: | ${{ steps.cloudflare_pages_deploy.outputs.deployment-alias-url }} |" >> $GITHUB_STEP_SUMMARY

      - name: Add URL of commit preview as commit status
        uses: actions/github-script@v6
        with:
          script: |
            const sha = context.payload.pull_request?.head.sha ?? context.sha;
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              context: 'Preview of commit',
              description: 'Click "Details" to check commit preview.',
              state: 'success',
              sha,
              target_url: "${{ steps.cloudflare_pages_deploy.outputs.deployment-url }}",
            });

      - name: Add URL of branch preview as commit status
        uses: actions/github-script@v6
        with:
          script: |
            const sha = context.payload.pull_request?.head.sha ?? context.sha;
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              context: 'Preview of branch',
              description: 'Click "Details" to check branch preview.',
              state: 'success',
              sha,
              target_url: "${{ steps.cloudflare_pages_deploy.outputs.deployment-alias-url }}",
            });
