name: Gatsby build and deploy to a development server
on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
      - name: Rewrite path-prefix
        run: |
          sed -i'' 's/pathPrefix:.*,/pathPrefix: `\/development`,/' gatsby-config.js
          grep 'pathPrefix:.*,' gatsby-config.js
      - name: Install Project Dependencies
        run: yarn install
      - name: Build Project
        run: npx gatsby build --prefix-paths
      - name: List output files
        run: ls -laFG
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: public/
          remote_path: ${{ secrets.PATH_PREVIEW }}
          remote_host: ${{ secrets.HOST_PREVIEW }}
          remote_user: ${{ secrets.USER_PREVIEW }}
          remote_key: ${{ secrets.KEY_PREVIEW }}
